Ajout des ressources PHP
abbealBZZZ/Ressources pull request #11
Opened 2021-04-16 15:47 UTC by juliobasito

Ajout de ressources PHP et GIT

2021-04-20 09:09 UTC, Haitaar requested changes
Remarque générale : Très cool la première personne mais on sait pas qui parle, c'est dommage !
Et si tu veux tu peux totalement parler au nom d'abbeal, en "on". T'en penses quoi ?

2021-04-20 09:09 UTC, Haitaar commented on php/drupal.md
> +* [Drupal 7 - Acquérir les fondamentaux](https://www.alphorm.com/tutoriel/formation-en-ligne-drupal-7-pour-tous-les-utilisateurs)
A voir avec Susie si tu penses que ça vaut le coup !

2021-04-20 09:09 UTC, Haitaar commented on versioning/README.md
> +# Ressources
Il faudrait ajouter une référence à cette seection sur le README root (idem pour PHP)

2021-04-21 08:29 UTC, juliobasito commented on php/README.md
> +Celle-ci vous permet de comprendre les nouveautés dans les dernières versions de PHP
Commentaire modifié

2021-04-21 08:30 UTC, juliobasito commented on php/drupal.md
> +* [Drupal 7 - Acquérir les fondamentaux](https://www.alphorm.com/tutoriel/formation-en-ligne-drupal-7-pour-tous-les-utilisateurs)
Je pense pas, a ma connaissance il n'y a pas de projet Drupal actuellement chez Abbeal. J'ai mis cette partie ou cas ou ça vienne à changer.

2021-04-21 08:30 UTC, juliobasito commented on versioning/README.md
> +# Ressources
README.md global modifié

2021-04-22 12:27 UTC, Haitaar approved these changes

2021-04-22 12:27 UTC, merged